routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    /*$users= \App\User::inRandomOrder()
        ->where('idfacultad',1)
        ->get();
    return $users;*/
    return view('welcome');
});

//Route::get()



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/admin/gestionarmodelo','ModeloController');
Route::resource('/admin/gestionarfacultad','FacultadController');
Route::resource('/admin/gestionartipousuario','TipoUsuarioController');
Route::resource('/admin/gestionarusuario','UsuarioController');
Route::resource('/admin/gestionarencuesta','EncuestaController');


Route::get('/admin/gestionarresultado','ResultadoController@index');
Route::get('/admin/gestionarresultado/{idencuesta}','ResultadoController@show');
Route::get('/admin/gestionarresultado/{idencuesta}/{idusuario}','ResultadoController@detalle');

Route::get('/admin/gestionarmiencuesta','MiEncuestaController@index');

resources/views/gestionarmodelo/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <p>{{ $error }}</p>
                    @endforeach()
                </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    Crear un nuevo modelo <a href="{{ route('gestionarmodelo.index') }}" class="btn btn-primary btn-round pull-right">Atras</a>
                </div>
                <div class="panel-body">
                    <form action="{{ route('gestionarmodelo.store') }}" method="POST" class="form-horizontal">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label class="control-label col-sm-2" >Descripcion</label>
                            <div class="col-sm-10">
                                <input type="text" name="descripcion" id="descripcion" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <input type="submit" class="btn btn-primary" value="Guardar" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/gestionarmodelo/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <p>{{ $error }}</p>
                    @endforeach()
                </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    Editar Modelo <a href="{{ route('gestionarmodelo.index') }}" class="btn btn-primary btn-round pull-right">Atras</a>
                </div>
                <div class="panel-body">
                    <form action="{{ route('gestionarmodelo.update',$modelo->id) }}" method="POST" class="form-horizontal">
                   {{-- <form action="{{ url('/admin/gestionarmodelo/'.$modelo->id) }}" method="PUT" class="form-horizontal">--}}
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="form-group">
                            <label class="control-label col-sm-2" >Descripcion</label>
                            <div class="col-sm-10">
                                <input type="text" name="descripcion" id="descripcion" value="{{$modelo->descripcion}}" class="form-control">
                                <input type="hidden" name="id" id="id" value="{{$modelo->id}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <input type="submit" class="btn btn-primary" value="Guardar" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/gestionarmodelo/index.blade.php
@extends('layouts.app')


@section('content')


   {{-- <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Items CRUD</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('gestionarmodelo.create') }}"> Crear Un Nuevo Modelo</a>
            </div>
        </div>
    </div>--}}


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="card card-plain">


        <div class="card-header" data-background-color="blue">
            <h4 class="title">Gestionar Modelos</h4>
            <p class="category">Modelos de Madurez</p>
        </div>
    </div>
    <div class="pull-right">
        <a class="btn btn-success" href="{{ route('gestionarmodelo.create') }}"> Crear</a>

       {{-- <button class="btn btn-success btn-round" href="{{ route('gestionarmodelo.create') }}">
            <i class="material-icons" >create</i> Crear
            <div class="ripple-container" ></div></button>--}}

    </div>

    <table class="table table-hover">
        <tr>
            <th>No</th>
            <th>Descripcion</th>
            <th width="280px">Accion</th>
        </tr>
        <tbody>
        @foreach ($modelos as $key => $modelo)
            <tr>
                <td class="table-text">
                    {{$modelo->id}}
                </td>
                <td class="table-text">
                    {{$modelo->descripcion}}
                </td>
                <td>
                    {{--<a href="{{ route('posts.details', $post->id) }}" class="label label-success">Details</a>--}}

                    <form action="{{ route('gestionarmodelo.destroy',$modelo->id) }}" method="POST" class="form-horizontal">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <a href="{{ route('gestionarmodelo.edit', $modelo->id) }}" class="btn btn-info btn-round">Editar</a>
                        <input type="submit" class="btn btn-danger btn-round" value="Eliminar" />
                    {{--<a href="{{ route('gestionarmodelo.destroy', $modelo->id) }}" class="btn btn-danger btn-round" onclick="return confirm('Esta seguro que quiere eliminar?')">Eliminar</a>--}}
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {!! $modelos->render() !!}


@endsection