routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    /*$users= \App\User::inRandomOrder()
        ->where('idfacultad',1)
        ->get();
    return $users;*/
    return view('welcome');
});

//Route::get()



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/admin/gestionarmodelo','ModeloController');
Route::resource('/admin/gestionarfacultad','FacultadController');
Route::resource('/admin/gestionartipousuario','TipoUsuarioController');
Route::resource('/admin/gestionarusuario','UsuarioController');
Route::resource('/admin/gestionarencuesta','EncuestaController');


Route::get('/admin/gestionarresultado','ResultadoController@index');
Route::get('/admin/gestionarresultado/{idencuesta}','ResultadoController@show');
Route::get('/admin/gestionarresultado/{idencuesta}/{idusuario}','ResultadoController@detalle');

Route::get('/admin/gestionarmiencuesta','MiEncuestaController@index');

resources/views/gestionarusuario/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <p>{{ $error }}</p>
                    @endforeach()
                </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    Crear un nuevo Usuario <a href="{{ route('gestionarusuario.index') }}" class="btn btn-primary btn-round pull-right">Atras</a>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('gestionarusuario.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Apellido</label>

                            <div class="col-md-6">
                                <input id="apellido" type="text" class="form-control" name="apellido" value="{{ old('apellido') }}" required>

                                @if ($errors->has('apellido'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('apellido') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Carnet Identidad</label>

                            <div class="col-md-6">
                                <input id="ci" type="number" class="form-control" name="ci" value="{{ old('ci') }}" required>

                                @if ($errors->has('ci'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('ci') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <?php $facultads = \App\Facultad::all() ?>

                        <div class="form-group">
                            <label for="sel1" class="col-md-4 control-label ">Facultad</label>
                            <select name="idfacultad" class="col-md-4 control-label" id="sel1">
                                @foreach($facultads as $facultad)
                                    <option value="{{$facultad->id}}">{{$facultad->descripcion}}</option>
                                @endforeach
                            </select>
                        </div>
                        <?php $tipousuarios = \App\TipoUsuario::all() ?>

                        <div class="form-group">
                            <label for="sel1" class="col-md-4 control-label ">Tipo Usuario</label>
                            <select name="idusuario" class="col-md-4 control-label" id="sel1">
                                @foreach($tipousuarios as $tipousuario)
                                    <option value="{{$tipousuario->id}}">{{$tipousuario->descripcion}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Correo Electronico</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/gestionarusuario/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <p>{{ $error }}</p>
                    @endforeach()
                </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    Editar Usuario <a href="{{ route('gestionarusuario.index') }}" class="btn btn-primary btn-round pull-right">Atras</a>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('gestionarusuario.update',$usuario->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $usuario->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Apellido</label>

                            <div class="col-md-6">
                                <input id="apellido" type="text" class="form-control" name="apellido" value="{{$usuario->apellido }}" required>

                                @if ($errors->has('apellido'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('apellido') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Carnet Identidad</label>

                            <div class="col-md-6">
                                <input id="ci" type="number" class="form-control" name="ci" value="{{ $usuario->ci }}" required>

                                @if ($errors->has('ci'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('ci') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <?php $facultads = \App\Facultad::all() ?>

                        <div class="form-group">
                            <label for="sel1" class="col-md-4 control-label ">Facultad</label>
                            <select name="idfacultad" class="col-md-4 control-label" id="sel1" >
                                @foreach($facultads as $facultad)

                                    <option value="{{$facultad->id}}"
                                            @if ($facultad->id == old('idfacultad', $usuario->idfacultad))
                                            selected="selected"
                                            @endif
                                    >{{$facultad->descripcion}}</option>
                                   {{-- <option value="{{$facultad->id}}">{{$facultad->descripcion}}</option>--}}
                                @endforeach
                            </select>
                        </div>
                        <?php $tipousuarios = \App\TipoUsuario::all() ?>

                        <div class="form-group">
                            <label for="sel1" class="col-md-4 control-label ">Tipo Usuario</label>
                            <select name="idtipousuario" class="col-md-4 control-label" id="sel1">
                                @foreach($tipousuarios as $tipousuario)

                                    <option value="{{$tipousuario->id}}"
                                            @if ($tipousuario->id == old('idfacultad', $usuario->idtipousuario))
                                            selected="selected"
                                            @endif
                                    >{{$tipousuario->descripcion}}</option>

                                    {{--<option value="{{$tipousuario->id}}">{{$tipousuario->descripcion}}</option>--}}
                                @endforeach
                            </select>
                        </div>
{{--
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Correo Electronico</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>--}}
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/gestionarusuario/index.blade.php
@extends('layouts.app')


@section('content')

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="card card-plain">
        <div class="card-header" data-background-color="blue">
            <h4 class="title">Gestionar Usuarios</h4>
            <p class="category">Usuarios de Madurez</p>
        </div>
    </div>
    <div class="pull-right">
        <a class="btn btn-success" href="{{ route('gestionarusuario.create') }}"> Crear</a>

    </div>

    <table class="table table-hover">
        <tr>
            <th>No</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>email</th>
            <th>ci</th>
            <th>TipoUsuario</th>
            <th>Facultad</th>
            <th width="280px">Accion</th>
        </tr>
        <tbody>
        @foreach ($usuarios as $key => $usuario)
            <tr>
                <td class="table-text">
                    {{$usuario->id}}
                </td>
                <td class="table-text">
                    {{$usuario->nombre}}
                </td>
                <td class="table-text">
                    {{$usuario->apellido}}
                </td>
                <td class="table-text">
                    {{$usuario->email}}
                </td>
                <td class="table-text">
                    {{$usuario->ci}}
                </td>
                <td class="table-text">
                    {{\App\TipoUsuario::findOrFail($usuario->idtipousuario)->descripcion}}
                    {{--{{$usuario->idtipousuario}}--}}
                </td>
                <td class="table-text">
                    {{\App\Facultad::findOrFail($usuario->idfacultad)->descripcion}}
                </td>
                <td>
                    <form action="{{ route('gestionarusuario.destroy',$usuario->id) }}" method="POST"
                          class="form-horizontal">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <a href="{{ route('gestionarusuario.edit', $usuario->id) }}" class="btn btn-info btn-round">Editar</a>
                        <input type="submit" class="btn btn-danger btn-round" value="Eliminar"/>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {!! $usuarios->render() !!}

@endsection